name: catodo
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  provider: ^6.1.2
  google_sign_in: ^6.2.2
  dartz: ^0.10.1
  equatable: ^2.0.7
  get_it: ^8.0.3
  injectable: ^2.5.0
  flame: ^1.16.0
  flame_tiled: ^1.18.4
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flame_riverpod: ^5.4.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  injectable_generator: ^2.6.2
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  assets:
    - assets/tiles/
    - assets/images/
    - assets/images/cat/
    - assets/images/cat/Cats/
    - assets/images/cat/Cats/Sprites/
